/***************************************************************************
 * The contents of this file were generated with Amplify Studio.           *
 * Please refrain from making any modifications to this file.              *
 * Any changes to this file will be overwritten when running amplify pull. *
 **************************************************************************/

/* eslint-disable */
import * as React from "react";
import { getOverrideProps } from "./utils";
import { Text, View } from "@aws-amplify/ui-react";
export default function Studentlist(props) {
  const { overrides, ...rest } = props;
  return (
    <View
      width="1728px"
      height="102px"
      display="block"
      gap="unset"
      alignItems="unset"
      justifyContent="unset"
      position="relative"
      padding="0px 0px 0px 0px"
      {...getOverrideProps(overrides, "Studentlist")}
      {...rest}
    >
      <View
        width="71.45px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="0%"
        right="95.87%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 231")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="54px"
        height="25px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="17.65%"
        left="0.98%"
        right="95.89%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="選択"
        {...getOverrideProps(overrides, "\u9078\u629E")}
      ></Text>
      <View
        width="183.33px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="4.13%"
        right="85.26%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 11")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="65.92px"
        height="26px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="58.82%"
        bottom="15.69%"
        left="8.77%"
        right="87.41%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="氏名"
        {...getOverrideProps(overrides, "\u6C0F\u540D")}
      ></Text>
      <View
        width="209.65px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="14.74%"
        right="73.12%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 13")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="104.53px"
        height="25px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="17.65%"
        left="18.64%"
        right="75.31%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="フリガナ"
        {...getOverrideProps(overrides, "\u30D5\u30EA\u30AC\u30CA")}
      ></Text>
      <View
        width="153.24px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="26.88%"
        right="64.25%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 259")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="82.87px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="14.71%"
        left="29.75%"
        right="65.45%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="大学名"
        {...getOverrideProps(overrides, "\u5927\u5B66\u540D")}
      ></Text>
      <View
        width="183.33px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="35.75%"
        right="53.65%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 269")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="101.7px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="14.71%"
        left="38.58%"
        right="55.53%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="説明会日時"
        {...getOverrideProps(overrides, "\u8AAC\u660E\u4F1A\u65E5\u6642")}
      ></Text>
      <View
        width="184.27px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="46.35%"
        right="42.98%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 279")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="147.85px"
        height="51px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="-7.84%"
        left="48.61%"
        right="42.83%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="一次面接日時"
        {...getOverrideProps(overrides, "\u4E00\u6B21\u9762\u63A5\u65E5\u6642")}
      ></Text>
      <View
        width="183.33px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="57.02%"
        right="32.37%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 289")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="144.08px"
        height="53px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="-9.8%"
        left="60%"
        right="31.66%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="座談会日時"
        {...getOverrideProps(overrides, "\u5EA7\u8AC7\u4F1A\u65E5\u6642")}
      ></Text>
      <View
        width="183.33px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="67.63%"
        right="21.76%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(252,255,235,1)"
        {...getOverrideProps(overrides, "Rectangle 304")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="146.9px"
        height="53px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="-9.8%"
        left="69.86%"
        right="21.63%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="最終面接日時"
        {...getOverrideProps(overrides, "\u5F79\u54E1\u9762\u63A5\u65E5\u6642")}
      ></Text>
      <View
        width="220.94px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="78.18%"
        right="9.03%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 14")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="210px"
        height="27px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="57.84%"
        bottom="15.69%"
        left="78.76%"
        right="9.09%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="当社を知ったきっかけ"
        {...getOverrideProps(
          overrides,
          "\u5F53\u793E\u3092\u77E5\u3063\u305F\u304D\u3063\u304B\u3051"
        )}
      ></Text>
      <View
        width="198.37px"
        height="47px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="63.73%"
        bottom="-9.8%"
        left="90.97%"
        right="-2.45%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(203,228,255,1)"
        {...getOverrideProps(overrides, "Rectangle 299")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="95px"
        height="28px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="56.86%"
        bottom="15.69%"
        left="94.5%"
        right="0%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="学生状況"
        {...getOverrideProps(overrides, "\u5B66\u751F\u72B6\u6CC1")}
      ></Text>
      <View
        width="1770.31px"
        height="65px"
        display="block"
        gap="unset"
        alignItems="unset"
        justifyContent="unset"
        position="absolute"
        top="0%"
        bottom="36.27%"
        left="0%"
        right="-2.45%"
        border="1px SOLID rgba(140,200,255,1)"
        padding="0px 0px 0px 0px"
        backgroundColor="rgba(198,235,255,1)"
        {...getOverrideProps(overrides, "Rectangle 10")}
      ></View>
      <Text
        fontFamily="Inter"
        fontSize="20px"
        fontWeight="400"
        color="rgba(0,16,102,1)"
        lineHeight="24.204544067382812px"
        textAlign="left"
        display="block"
        direction="column"
        justifyContent="unset"
        width="145.96px"
        height="30px"
        gap="unset"
        alignItems="unset"
        position="absolute"
        top="6.86%"
        bottom="63.73%"
        left="48.34%"
        right="43.22%"
        padding="0px 0px 0px 0px"
        whiteSpace="pre-wrap"
        children="学生一覧"
        {...getOverrideProps(overrides, "\u5B66\u751F\u4E00\u89A7")}
      ></Text>
    </View>
  );
}
